### ISSUE TITLE
How add a block

### ISSUE THREAD

**Issue by kamalkech** [Invulu/organic-profile-block#1]
I follow the intructions but i can't found : 

3. Within a post or page, select the '+' symbol to add a new block.

can you share a capture ?

**Comment by cocodedesigns** [comment]
@kamalkech 

The + symbol is the plus inside the circle that appears whenever you hover over the space after a Gutenberg element.  It's the button you click to add any other Gutenberg block.

![Screenshot of "Insert Block" button, within the editor](https://user-images.githubusercontent.com/5691375/38158769-8b1a159e-3492-11e8-85c9-c6994a81ab40.png)

You can also view it at the top of the Gutenberg editor, underneath the WordPress Admin Bar.

![Screenshot of "Insert Block" button, underneath the Admin Bar](https://user-images.githubusercontent.com/5691375/38158930-db6e4e4a-3495-11e8-8db9-2636ea3c3e48.png)

However, @Invulu, I want to add to this issue, since there is a problem (that I can see, at least).  This ticket is looking at adding _**a**_ block, but I am having trouble adding **_your_** block.  In the instructions, you said "4. From the 'Blocks' tab, select the 'Profile' block."  There's a nifty little search bar at the top of the block insert tabs, so I typed in there to find the Profile block.  This is all I saw when I typed in "Pr".

!["Insert Block" search results for "Pr"](https://user-images.githubusercontent.com/5691375/38158913-392075dc-3495-11e8-9dbe-76a8067a6cf3.png)

I type in "Pro", and I see nothing.

!["Insert Block" search results for "Pro"](https://user-images.githubusercontent.com/5691375/38158960-5798dad0-3496-11e8-8ef1-0f56d6f5ed67.png)

From what I can see, the Profile block is not listed.  I have tried this on a fresh install of WordPress (version 4.9.4) as well with only Gutenberg (version 2.5.0) and OCP (version 1.0.1) active on the Twenty Seventeen theme (version 1.4).  I know some updates have been released for Gutenberg in the last few weeks, and some today I think, so I'm not sure if something has borked in that time?

**Comment by cocodedesigns** [comment]
Also @itsdavidmorgan

**Comment by kamalkech** [comment]
@cocodedesigns 

I download last version of wordpress and last version of this plugin, i look for button + and nothing found it, check captures : 

![1](https://user-images.githubusercontent.com/1313428/38162457-8ab58100-34d9-11e8-8971-40af3fc495c6.png)
![2](https://user-images.githubusercontent.com/1313428/38162458-8adc2b66-34d9-11e8-8aed-c0ccdf5292f3.png)

**Comment by dkrape** [comment]
It is possible you are not seeing the block due to issue #2.

However, I added the fix noted in the issue and receive a different error:

```Invariant Violation: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings." ```

**Comment by metalandcoffee** [comment]
Just wanted to add that I got to the same point as @dkrape. Would love to see it working!

**Comment by itsdavidmorgan** [comment]
Hey guys! I've pushed some updates to the plugin that should resolve these issues. Gutenberg made some changes that rendered the old version obsolete. It should be working as expected now. :)
